spring:

  application:
    name: impl

  datasource:
    generate-unique-name: false
    name: tacocloud

  cassandra:
    keyspace-name: taco_cloud
    schema-action: recreate
    local-datacenter: datacenter1
    username: tacocloud
    password: s3cr3tP455w0rd
